apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: competition-ops-bot-i
spec:
  capacity:
    storage: 16Gi
  storageClassName: standard-csi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: competition-ops-bot-i
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-csi
  resources:
    requests:
      storage: 16Gi

