apiVersion: v1
kind: ConfigMap
metadata:
  name: discord-environment
data:
  DISCORD_GUILD: "<GUILD_ID>"
  DISCORD_APP: "<APP_ID>"
  BLUE_TEAMS: "<NUM_BLUE_TEAMS>"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-environment
data:
  DB_USER: "cobi"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: "cobi"