apiVersion: v1
kind: Secret
metadata:
  name: discord-token
  namespace: competition-ops-bot-i
type: Opaque
data:
  token: <B64_SESSION_TOKEN>
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
  namespace: competition-ops-bot-i
type: Opaque
data:
  password: <B64_DB_PASSWORD>
